New NZGD data map
ucgmsim/nzgd_map pull request #1
Opened 2024-12-06 00:53 UTC by AndrewRidden-Harper

The new NZGD data map is based on @lispandfound 's [template](https://github.com/ucgmsim/webplate) and is temporarily hosted at http://hypocentre:5000/ if you want to try it

2024-12-06 01:03 UTC, sungeunbae approved these changes

2024-12-08 22:10 UTC, lispandfound approved these changes

2024-12-08 22:10 UTC, lispandfound commented on app/views.py
> +            combined_soil_str = combined_soil_str.strip(" + ")
```suggestion
            combined_soil_str = " + ".join(soil_type)
```

2024-12-08 22:10 UTC, lispandfound commented on app/templates/base.html
> +    </script>
This is a very big JS payload. You only use it on `index.html`. Consider moving this to the scripts block inside `index.html`.

That would be removing the above code and adding the following to index.html.
```
{% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <script>
        window.addEventListener('load', function() {
            MathJax.typeset();
        });
    </script>
{% endblock %}
```

2024-12-08 22:11 UTC, lispandfound requested changes
See the requested changes.

2024-12-09 02:10 UTC, lispandfound approved these changes

2024-12-10 20:20 UTC, joelridden commented
Maybe when the Vs30 values are nan in the table to remove them e.g. (boore_2004 less than 10 meters)

2024-12-10 20:21 UTC, joelridden reviewed
Maybe when the Vs30 values are nan in the table to remove them e.g. (boore_2004 less than 10 meters)

2024-12-11 22:33 UTC, AndrewRidden-Harper commented
Now it only shows Vs30 results for Vs to Vs30 correlations that are valid given the CPT's maximum depth. For the map display, if the selected Vs to Vs30 correlation does not allow a Vs30 value to be calculated, an explanation is shown in the map marker's hover text

2024-12-12 20:05 UTC, joelridden approved these changes

2024-12-13 02:48 UTC, merged